@tool
extends SceneTree

# Generates gdpp/godot.vim, the names of Godot's types, and gdpp/notifications.vim, the names of its
# notifications, as on blocks name them, from the running Godot: `make gen`.

func _init() -> void:
  var builtin_types = " Variant"
  var obj_classes = ""
  var ref_classes = ""
  var node_classes = ""

  for type in range(TYPE_MAX):
    if type != TYPE_NIL and type != TYPE_OBJECT:
      builtin_types += " " + type_string(type)

  for cls in ClassDB.get_class_list():
    if ClassDB.is_parent_class(cls, "RefCounted"):
      ref_classes += " " + cls
    elif ClassDB.is_parent_class(cls, "Node"):
      node_classes += " " + cls
    else:
      obj_classes += " " + cls

  # NOTIFICATION_READY is "ready", as in on ready { ... }. Classes share some, e.g. visibility_changed.
  var notifications: Array[String] = []
  for cls in ClassDB.get_class_list():
    for constant in ClassDB.class_get_integer_constant_list(cls, true):
      var name: String = constant.trim_prefix("NOTIFICATION_").to_lower()
      if constant.begins_with("NOTIFICATION_") and not notifications.has(name):
        notifications.append(name)
  notifications.sort()

  var version: String = Engine.get_version_info().string
  var file := FileAccess.open("gdpp/notifications.vim", FileAccess.WRITE)
  file.store_line("\" Generated by gen.gd from Godot " + version + ", with `make gen`. Don't edit.")
  file.store_line("syntax keyword gdppNotification contained nextgroup=gdppOnArgs,gdppCppBlock skipwhite skipempty " + " ".join(PackedStringArray(notifications)))
  file.close()

  file = FileAccess.open("gdpp/godot.vim", FileAccess.WRITE)
  file.store_line("\" Generated by gen.gd from Godot " + version + ", with `make gen`. Don't edit.")
  file.store_line("syntax keyword godotBuiltinType" + builtin_types)
  file.store_line("syntax keyword godotObjClass" + obj_classes)
  file.store_line("syntax keyword godotRefClass" + ref_classes)
  file.store_line("syntax keyword godotNodeClass" + node_classes)
  file.close()
  quit()
