@tool
extends SceneTree

# Generates gdpp/godot.vim, the names of Godot's types, from the running Godot: `make gen`.

func _init() -> void:
  var builtin_types = " Variant"
  var obj_classes = ""
  var ref_classes = ""
  var node_classes = ""

  for type in range(TYPE_MAX):
    if type != TYPE_NIL and type != TYPE_OBJECT:
      builtin_types += " " + type_string(type)

  for cls in ClassDB.get_class_list():
    if ClassDB.is_parent_class(cls, "RefCounted"):
      ref_classes += " " + cls
    elif ClassDB.is_parent_class(cls, "Node"):
      node_classes += " " + cls
    else:
      obj_classes += " " + cls

  var file := FileAccess.open("gdpp/godot.vim", FileAccess.WRITE)
  file.store_line("\" Generated by gen.gd from Godot " + Engine.get_version_info().string + ", with `make gen`. Don't edit.")
  file.store_line("syntax keyword godotBuiltinType" + builtin_types)
  file.store_line("syntax keyword godotObjClass" + obj_classes)
  file.store_line("syntax keyword godotRefClass" + ref_classes)
  file.store_line("syntax keyword godotNodeClass" + node_classes)
  file.close()
  quit()
